
POST http://127.0.0.1:8000/thread
Content-Type: application/json
access_token: 76b77f8749a14af4b2ae0ff591bcf398

###

POST http://127.0.0.1:8000/message
Content-Type: application/json
access_token: 76b77f8749a14af4b2ae0ff591bcf398

{
    "message": "",
    "thread_id": "thread_5zeBZKmFBVULJzHJvm0CxwDY"
}

###